version: "3.9"
services:
  mineskin-api:
    image: ghcr.io/mineskin/mineskin-api:latest
    container_name: mineskin-api
    environment:
      FORCE_COLOR: 1
      NODE_ENV: ${NODE_ENV}
      DOTENV_KEY: ${DOTENV_KEY}
      HOST_HOSTNAME: $HOSTNAME
      NODE_HOSTNAME: '{{.Node.Hostname}}'
    #network_mode: host
    networks:
      - host
    volumes:
      - /home/inventivetalent/api.mineskin.org/config.js:/opt/app/config.js
      - /home/inventivetalent/api.mineskin.org/logs:/opt/app/logs
    deploy:
      replicas: 6
      placement:
        constraints: [node.labels.mineskin-api == true]
      update_config:
          parallelism: 1
          delay: 10s

networks:
  host:
    name: host
    external: true