version: "3.9"
services:
  mineskin-api:
    image: ghcr.io/mineskin/mineskin-api:latest
    container_name: mineskin-api
    environment:
      FORCE_COLOR: 1
      NODE_ENV: ${NODE_ENV}
      DOTENV_KEY: ${DOTENV_KEY}
      HOST_HOSTNAME: $HOSTNAME
      NODE_HOSTNAME: '{{.Node.Hostname}}'
    #network_mode: host
    networks:
      - host
    volumes:
      - /home/inventivetalent/api.mineskin.org/config.js:/opt/app/config.js
      - /home/inventivetalent/api.mineskin.org/logs:/opt/app/logs
      - type: bind
        source: /home/inventivetalent/api.mineskin.org/.well-known
        target: /opt/app/.well-known
        bind:
          create_host_path: true
      - /home/inventivetalent/api.mineskin.org/flagsmith.json:/opt/app/flagsmith.json
    stop_grace_period: 2m
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:3017/health || exit 1"
      interval: 5m
      start_period: 1m
      timeout: 3s
      retries: 3
    deploy:
      replicas: 5
      placement:
        max_replicas_per_node: 1
        constraints: [node.labels.mineskin-api == true]
        preferences:
          - spread: node.id
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.5'
          memory: 450M

networks:
  host:
    name: host
    external: true