version: "3.9"
services:
  mineskin-api:
    image: ghcr.io/mineskin/mineskin-api:ipv6
    container_name: mineskin-api
    environment:
      FORCE_COLOR: 1
      NODE_ENV: ${NODE_ENV}
      DOTENV_KEY: ${DOTENV_KEY}
      HOST_HOSTNAME: $HOSTNAME
      NODE_HOSTNAME: '{{.Node.Hostname}}'
    #network_mode: host
    networks:
      - host
    volumes:
      - /home/inventivetalent/api.mineskin.org/config.js:/opt/app/config.js
      - /home/inventivetalent/mineskin.jwt.private.key:/etc/mineskin/mineskin.jwt.private.key
    secrets:
      - mineskin.jwt.private.key
    deploy:
      replicas: 5
      placement:
        constraints: [node.labels.mineskin-api == true]
      update_config:
          parallelism: 1
          delay: 5s

secrets:
  mineskin.jwt.private.key:
    file: /home/inventivetalent/mineskin.jwt.private.key
    external: true

networks:
  host:
    name: host
    external: true